# Generated by Django 6.0 on 2025-12-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_application_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='application',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
