# Generated by Django 6.0 on 2025-12-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_application_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод по номеру телефона')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(default='2025-01-01', verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, verbose_name='Дополнительные пожелания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование курса'),
        ),
    ]
